name: LIVE365
description: Next TikTok App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "any"
  firebase_auth: "any"
  firebase_database: "any"
  cloud_firestore: ^0.14.2
  firebase_storage: "any"
  google_sign_in: "^4.5.1"
  cached_network_image:
  webview_flutter: ^1.0.1
  shared_preferences: ^0.5.12+4
  http_auth: ^0.3.2
  chewie:
  flutter_launcher_icons: 0.7.5
  agora_rtc_engine: ^3.1.3
  agora_rtm: ^0.9.11
  sliding_up_panel: ^1.0.2
  wakelock: ^0.1.4+1
  permission_handler: ^3.0.0
  url_launcher: ^5.7.10
  font_awesome_flutter: 8.8.1
  gradient_text: 1.0.2
  image_picker: ^0.6.7+12
  flare_flutter:
  random_color: ^1.0.5
  ff_navigation_bar: ^0.1.5
  responsive_builder: ^0.2.0+2
  marquee: ^1.5.2
  camera: ^0.5.8+2
  carousel_slider: ^2.2.1
  stacked_services: 0.5.4+3
  get_it: ^5.0.0
  stacked: ^1.7.6
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  open_file: ^3.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  line_icons:
  video_player: ^0.10.11+2
  flutter_svg: ^0.18.0
  intl: 0.16.1
  date_range_picker: ^1.0.5
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  dio: ^3.0.10
  uuid: 2.0.1
  timeago: ^2.0.28
  like_button: ^1.0.4
  image_cropper: ^1.3.1
  videos_player: ^0.1.3
  flutter_icons: ^1.1.0
  percent_indicator: ^2.1.8
  fluttertoast: ^7.1.1
  animations: ^1.1.2
  image: ^2.1.18
  google_fonts: ^1.1.1
  provider: ^4.3.2+3
  modal_progress_hud: ^0.1.3
  flutter_facebook_auth: ^2.0.2
  flutter_facebook_login: ^3.0.0
  screen: ^0.0.5 # keeping screen on

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gift/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

fonts:
  fonts:
    - asset: assets/fonts/SFProDispaly-Regular.ttf
    - asset: assets/fonts/SFProDisplay-Black.ttf
    - asset: assets/fonts/SFProDisplay-Blod.ttf
      weight: 700
    - asset: assets/fonts/SFProDisplay-Heavy.ttf
    - asset: assets/fonts/SFProDisplay-Light.ttf
      weight: 300
    - asset: assets/fonts/SFProDisplay-Medium.ttf
    - asset: assets/fonts/SFProDisplay-semibold.ttf
    - asset: assets/fonts/SFProDisplay-Thin.ttf
    - asset: assets/fonts/SFProDisplay-Ultralight.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
